gohelpfund-web:
  image: gohelpfund/ghf-web-app:latest
  mem_limit: 553741824
  ports:
  - "80:80"
  environment:
    PROFILE: "prod-web"
    PLATFORM_ENV: "prod"
    SERVER_PORT: "80"
    REST_API_URI: "http://api.gohelpfund.com:5555"

