ghf-web-app:
  image: gohelpfund/ghf-web-app:${BUILD_NAME}
  cpu_shares: 2048
  mem_limit: 1700MB
  ports:
    - "443:443"
    - "80:80"
  environment:
    OPENSSL_KEY:            $HTTPS_OPENSSL_KEY
    OPENSSL_IV:             $HTTPS_OPENSSL_IV
    PROFILE:                "dev-web"
    REACT_APP_ENV:          "dev"
    REACT_APP_SEGMNET_KEY:  "fk98GwKbKa5nKJwPCzm89tfBJuVnM5kn"