gohelpfund-web:
  image: gohelpfund/ghf-web-app:latest
  mem_limit: 553741824
  ports:
  - "80:80"
  environment:
    PROFILE: "dev-web"
    PLATFORM_ENV: "dev"
    SERVER_PORT: "80"
    REST_API_URI: "http://dev-api.gohelpfund.com"

