ghf-web-app:
  image: gohelpfund/ghf-web-app:latest
  ports:
  - "443:443"
  environment:
    $NGINXSERVER_PORT:      "443"
    OPENSSL_KEY:            $HTTPS_OPENSSL_KEY
    OPENSSL_IV:             $HTTPS_OPENSSL_IV
